### ISSUE TITLE
Winのchrome版が起動しなくなっています

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nadesiko3webkit#10]
nadesiko3.exeを起動すると、一瞬フォームが開きかけるのですが、そのまま即落ちてしまいます。
webview2版では問題なくchrome版だけで発生します。
以前は動いていた旧バージョンから最新のv3.4.13まで同現象なので、chromeさんがバージョンアップしてどうにかなったのかも知れませんが、ご確認をお願いします。
chromeさんのバージョン：117.0.5938.92　（最新）です。

**Comment by kujirahand** [comment]
Chromeの起動で、WebSocketのエラーが出ていました。
オプションを追加することで、この問題をスキップできました。

**Comment by snowdrops89** [comment]
確認しました☆ありがとうございます！

**Comment by kujirahand** [comment]
@snowdrops89 確認ありがとうございました！
無事に起動するようになって良かったです。
